version: '3.8'

services:
  api1:
    build:
      context: ./api1
      dockerfile: Dockerfile
    container_name: api1_container
    networks:
      - custom_network
    ports:
      - "5001:5001"

  api2:
    build:
      context: ./api2
      dockerfile: Dockerfile
    container_name: api2_container
    networks:
      - custom_network
    ports:
      - "5002:5002"
    depends_on:
      - api1

networks:
  custom_network:
    driver: bridge
